### ISSUE TITLE
電気関連引越し手続き

### ISSUE THREAD

**Issue by rinaumeda** [cliu-nature/Chang-Liu#23]
- [x] GIO：メール送信

（メール内容：https://docs.google.com/document/d/1p2Eb_CdsqtmxZVncEw4J_d-Aq70nVov1-CWgtHBBncY/edit）

- [x] RPS：[電気事業者の氏名等変更届出書](https://docs.google.com/document/d/1kAHlsaZQOyGij1t5eeSgkeGjlQJoPFFY/edit)を経済産業省 資源エネルギー庁 新エネルギー課 再生可能エネルギー推進室に提出

- [x] 経産省関連：移行後２週間以内に[小売電気事業氏名等変更届出書](https://docs.google.com/document/d/1IJC9AqFB0As-Klk3qo9D1DyEzqlCE1Ls/edit)を提出

- [x] 広域機関システム：[会員情報変更](https://member-occto.occto.or.jp/login)

- [x] 託送システム：９地域に一括メール送信

- [x] GMO-PG：IP関連問い合わせ中（金曜日には終わる予定）

**Comment by cliu-nature** [comment]
メモ
経産省関連：木下さんに送付を依頼済
託送システム：9エリア送信済　⇒返信待ち
